name: t3aisat
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  flutter_dotenv: ^5.1.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  collection: 1.18.0  # Compatible
  http_parser: ^4.0.2  # Recommend the recommended version
  leak_tracker: 10.0.4  # Compatible
  leak_tracker_flutter_testing: 3.0.3  # Compatible
  material_color_utilities: 0.8.0  # Compatible
  meta: 1.12.0  # Compatible
  test_api: 0.7.0  # Compatible
  vm_service: 14.2.1  # Compatible

flutter:
  uses-material-design: true
  assets:
    - .env.development
    - .env.production
